### ISSUE TITLE
Feature request: a tab showing a decent air pollution map + better collaboration with stuttgart.maps

### ISSUE THREAD

**Issue by WiliTest** [sensebox/openSenseMap#290]
● Currently, your map only shows the number of sensors of any type, per region, which is interesting but not really useful (for us). It would be more interesting to show a specific map such as "air pollution map" and focus on a way to improve  http://stuttgart.maps.luftdaten.info/  (open source).
The stuttgart.maps isn't really useful either: it doesn't explain the data shown on its map is : does it show the last reading or the average? And how to get an idea of the week/month data?  It doesn't show any graph, the users can't even add some comments on their sensor, (and, optional, a picture). And the worst part is that it's not automatic: you need to wait weeks (months?) before someone registers the sensor on their map ― if you are lucky. 

 So a combination of the two maps would provide a decent solution: automatic, showing the color of pollution is a basic (Stuttgart does it), adding a tiny graph of PM (or such) on mouse over and info chosen by the user (as you nearly offer) would be great.

● A better cooperation between openSenseMap and stuttgart.maps:
And it's also quite dramatic you get so few data from the Stuttgart team. They offer the option to put the data in openSenseMap but you have to find it by yourself in the middle of complex settings, so few people do it. That should be automatic, and even better, they should send the data sensor in a place that could be accessed by any open source projects (maybe by offering the users to hide some info, such as the precise location of their sensor). 

It's quite a waste of energy and dramatic to build and maintain to 2 maps and in the final to don't have any good one. 

Anyway, thanks for sharing your work!

**Comment by robarto** [comment]
Thanks for your comments.
please let me answer some of your points:

- Currently, your map only shows the number of sensors of any type, per region, which is interesting but not really useful (for us). It would be more interesting to show a specific map such as "air pollution map" and focus on a way to improve http://stuttgart.maps.luftdaten.info/ (open source).

This would be interesting for you, but not for a lot of other people. The approach of openSenseMap is to give access to live and historic raw open data from open source environmental measurement devices (as senseBox, airrohr from luftdaten, hackair or other devices). the approach is more general than the one from luftdaten, which focuses on air quality - in particular (sic!) particular matter ;) openSenseMap is more like openStreetMap, anybody can submit any kind of measurement on any kind of environmental phenomenon with any kind of device. 
In this approach and for most users of openSenseMap it is very important to know the position of each device as only at this position the displayed measurement is correct. interpolations - as we offer in an optional tab - and luftdaten offers in the main map view - are nice visualizations, but they don't reflect the real situation. it is very vague to generalize on air quality of large areas based on a few measurement points. interpolations in this case are just one cartographic method, that every person who has the access on the data can decide on.  

anyway, we understand the power but also the possible misunderstanding of (and possible manipulation through) interpolations and can imagine to continue to work on optional interpolations of data on openSenseMap. the current interpolation is not in a final state. 

- And it's also quite dramatic you get so few data from the Stuttgart team. They offer the option to put the data in openSenseMap but you have to find it by yourself in the middle of complex settings, so few people do it. That should be automatic, and even better, they should send the data sensor in a place that could be accessed by any open source projects (maybe by offering the users to hide some info, such as the precise location of their sensor).

Well, here again it is a different approach of different platforms. openSenseMap does not scrape data from other platforms as i.e. hackair, OpenAQ and others do. we follow an intrinsic motivation of the unique citizen scientist / organisation to share the data from her device to openSenseMap. that's why we are fine to only have approx. 20% of the luftdaten.info devices on openSenseMap. these are people who actively decided to do so because they believe that it makes sense. we know that we could access the rest of the data. 

- It's quite a waste of energy and dramatic to build and maintain to 2 maps and in the final to don't have any good one.

I agree on this point in general. There are a few platforms that do same or similar things as openSenseMap, where energy could have been used to improve openSenseMap, this is an classical problem of reuse of open source solutions. But luftdaten.info is a very specialized case (as the name already says). Nevertheless, we were and are in touch with a few colleagues from luftdaten.info and know about the similarities and differences. 

- Anyway, thanks for sharing your work!

You're welcome!

**Comment by WiliTest** [comment]
Thank you very much for your clear explaination!  I still think it's a huge waste to get  so few data from the  luftdaten.info sensor, but it might be better in the future.

 Just by curiosity, do you also store/share the _precise_ gps location of these sensors?

**Comment by mpfeil** [comment]
> Just by curiosity, do you also store/share the _precise_ gps location of these sensors?

To answer your question after a long time. We are storing the _gps location_ as the user provides it. During the registration you have the chance to modify the location of the device. So it could be a _precise_ or a not _precise_ gps location.

As this issue is quite old I am going to close it.
