### ISSUE TITLE
Change color of buttons.

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/OpenSenseMap#3]
Change green color to appropriate color fitting to sensebox colors.

**Comment by janwirwahn** [comment]
What about marking senseBoxes without sensors [1] or without any measurements [2] in grey?
Others should have same color (until further notice).

[1] http://opensensemap.org/#/explore/56c0b27f2cb6e1e410564aff
[2] http://opensensemap.org/#/explore/55f5b455b3de1fe005b398c3

**Comment by chk1** [comment]
Senseboxes without sensors: Should not be allowed during registration, since there's also no way to edit sensors at this point.

Senseboxes without data: Gray and/or somewhat transparent would have been my suggestion.

Maybe apply gray/transparent also to filtered boxes (with timeslider, tbd.), or simply don't show them at all.

**Comment by chk1** [comment]
I added some colour to the menu buttons
