### ISSUE TITLE
Luftdaten senseBox: changing the temperature/humidity sensor without registering a new senseBox

### ISSUE THREAD

**Issue by MagTun** [sensebox/openSenseMap#321]
I was using a luftdaten sensor with a DHT22 but I recently switched to a BME280. 
I no longer get temperature/humidity data on opensensemap. 
I could register a new senseBox but then my data won't be continuous. 
I went to the `edit/sensors` page and tried to add a new sensor, but I don't get any ID once I save the new sensor. 

So my question is: is there a way to switch my luftdaten-dht22 senseBox to a luftdaten-BME280 while keeping the same senseBox ID?

Thanks,

**Comment by ubergesundheit** [comment]
Hi MagTun,

changing the model of the sensor is possible, but strongly discouraged. The measurements up until the point of the model change are done with your DHT22 sensor but after the change it would look like if all measurements had been done with your BME280.

Your approach of adding a new sensor was the right way. Maybe you didn't saved the whole box after adding the sensor? The button on the top right should save the whole box and the new sensor should be added.

Otherwise, updating the sensor directly is possible through the API. https://docs.opensensemap.org/#api-Boxes-updateBox

**Comment by MagTun** [comment]
Yes you're right, I forgot to  save the whole sensebox at the top.
