### ISSUE TITLE
bower install does not inject bootstrap-language

### ISSUE THREAD

**Issue by mpfeil** [sensebox/OpenSenseMap#49]

**Comment by chk1** [comment]
Fixed by using this line in `bower.json`:

```
"bootstrap-languages": "https://github.com/usrz/bootstrap-languages.git#3ac2a3d"
```

**Comment by chk1** [comment]
Also relevant, just in case a future package update breaks: https://github.com/bower/bower.github.io/commit/5fb9b63#commitcomment-12590301

Bower changed its specs, so that compiled/minified files should no longer be in the package's bower.json in the `main` section. Seems to affect just a few packages at this time.
