### ISSUE TITLE
Invalid JSON if no data

### ISSUE THREAD

**Issue by niccokunzmann** [sensebox/OpenSenseMap#80]
Querying

     http://demoapi.opensensemap.org/boxes/5719c4037514d05c121e317c/data/5719c4037514d05c121e3180

has no data. The response is

    ]

**Comment by FelixErdmann** [comment]
You used the database ID of the sensor instead of the sensor_id itself. Please use the sensor_id.

You can find your all of your sensor_id's here:

[http://demoapi.opensensemap.org/boxes/5719c4037514d05c121e317c/sensors
](http://demoapi.opensensemap.org/boxes/5719c4037514d05c121e317c/sensors) 

,in your .ino sketch or in your registration e-mail.

**Comment by niccokunzmann** [comment]
Could one return an HTTP error code and a json object with a description?

**Comment by chk1** [comment]
This should be fixed now, I added some more error codes (400, 404) in case of 'no data'
